### ISSUE TITLE
Add fan pages support

### ISSUE THREAD

**Issue by afterdelight** [harismuneer/Ultimate-Facebook-Scraper#14]
When I try to scrap uploaded photos and videos on fan pages, it resulted with this

```
Photos..
Scraping Links..
Exception (scrap_data) 0 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrap_data) 1 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Photos Done
----------------------------------------
Videos:
Exception (scrap_data) 0 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrap_data) 1 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Videos Done
----------------------------------------
```
It only worked for scraping posts.

Thank you!

**Comment by github-userx** [comment]
I second this. Would be great if we could get the albums and photos of for example our favorite TV show's Facebook page. (Preferably sorted and kept in their original albums names)

**Comment by harismuneer** [comment]
@afterdelight, @github-userx. Making it work for the pages and videos of FB pages is a quite easy thing to do. You just have to see the relevant xpaths of the divs and replace it in the code where I am initializing the divs lists for photos and videos. 

Actually I am quite busy with other things these days, and maintaining this scraper is quite a task to do since Facebook updates its site and consequently the divs get changed and we have to update the divs again. Its a cat and mouse game. Anyways you guys can update the divs I mentioned for pages and it will work perfect.
