### ISSUE TITLE
I cant scrape anyting from public pages

### ISSUE THREAD

**Issue by Lxhnnn** [harismuneer/Ultimate-Facebook-Scraper#151]
**Describe the bug**

**To Reproduce**
1. Configure '…'
2. Run '…'
3. …

**Expected behavior**

**Screenshots or command output**
If applicable, add screenshots or `output logs` to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Python version [e.g. 3.7.5]
 - Chrome web driver version [e.g 81]

**Additional context**

**Comment by Andrew-Pulley** [comment]
@Lxhnnn, your post is pretty unclear.

However, I can confirm I'm experiencing the same issue.

**Describe the Bug**
A properly run script returns no results in the output files on a fully public Facebook profile.

**To Reproduce**

1. Config: 1 profile in input.txt
2. Run: `python scraper/scraper.py`
3. Script runs to completion.  Chrome loads and runs in an automated fashion including scrolling.
4. System prints numerous `NoSuchElementException`s, files are generated, but no data exists in those files, except for `Posts.txt` which contains a pipe-delimited header.

**Expected behavior**
Data to be output to files in the generated `data` folder.

**Screenshots or command output**
----------------------------------------
Scraping Friends..
Exception (scrape_data) 0 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 2 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 3 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 4 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 5 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 6 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 7 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Friends Done!
----------------------------------------
Scraping Photos..
Exception (scrape_data) 0 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Photos Done!
----------------------------------------
Scraping Videos..
Exception (scrape_data) 0 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Videos Done!
----------------------------------------
Scraping About..
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
About Done!
----------------------------------------
Scraping Posts..
Posts Done!

**Desktop (please complete the following information):**

- OS: MacOS 10.14.15
- Python Version: 3.8.3
- Chrome web driver version: ChromeDriver 84.0.4147.30

**Additional context**
I modified the code to print the exact exception.  I searched for the XPaths in Chrome Dev tools, and even broke down the selectors to individual class selectors, and was not able to find anything.  Wondering if a new release re-uglified all the selectors. The index error on the About scrape is another story that I didn't dive into.

Scrolling worked without issue.

**Comment by Lxhnnn** [comment]
When I crawled the public page about LeBron , the following happened.

Scraping: https://www.facebook.com/LeBron
----------------------------------------
Scraping Friends..
Exception (scrape_data) 0 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 2 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 3 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 4 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 5 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 6 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 7 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Friends Done!
----------------------------------------
Scraping Photos..
Exception (scrape_data) 0 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Photos Done!
----------------------------------------
Scraping Videos..
Exception (scrape_data) 0 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Videos Done!
----------------------------------------
Scraping About..
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
About Done!

**Comment by Andrew-Pulley** [comment]
I have another update and clarification: My attempts to scrape were on both Facebook's Beta site, and Facebook Classic.  Both returned the same result.

**Comment by Lxhnnn** [comment]
Now, it looks like I can’t  switch to classic FB UI

**Comment by Sajjadkhan12** [comment]
[http://prosourcecode.com/](url)

**Comment by christopherhastings** [comment]
I experienced the same issue. 

Launches and scrolls through the post successfully, but does not scrape any information.

OS 10.15 
Python 3.7.6
ChromeDriver 2.24.1

**Comment by Nellix** [comment]
I think we need to update the code using the new FB UI code.

**Comment by deepa1-d** [comment]
How selectors.json and params.json needs to be changed according to current UI ?

**Comment by harismuneer** [comment]
### 📢 Important Announcement: UFS 2.0 (with support for latest Facebook UI)

Hi guys! The exclusive version of **UFS 2.0** supports scraping for the latest Facebook UI along with many powerful features, much better organization through CSV (Excel-like) file format, bug fixes, and multiple browser support. You can get exclusive access here: 

#### **[Buy UFS 2.0](https://tinyurl.com/UFS-NEW)** 

Building the new version has been a tough technical challenge and I have spent a considerable amount of time and effort on building it. Therefore, kindly support by purchasing it from the link shared [above.](https://tinyurl.com/UFS-NEW) 

<hr>
You can also share small donations through these links:


- <a href="https://buy.paddle.com/product/638653"><b>Platinum (99.99$)</b> -> 2 hours of development<a/>
- <a href="https://buy.paddle.com/product/638651"><b>Gold (49.99$)</b> -> 1 hour of development</a>
- <a href="https://buy.paddle.com/product/638654"><b>Silver (19.99$)</b> -> 30 minutes of development</a>

_If **considerable support is shown through the above donations then I will release the version for the general public** after some time as I want to keep this software open-sourced. So, now is the time for all those folks who benefited from the tool to support its reach for a wider audience :)_
