### ISSUE TITLE
You've been temporarily blocked - Facebook

### ISSUE THREAD

**Issue by InsaneJokerr** [harismuneer/Ultimate-Facebook-Scraper#48]
The script is moving to quickly and results in Facebook blocking an account from viewing pages. Error is: 

You've been temporarily blocked
It looks like you were misusing this feature by going too quickly. You've been blocked from using it.

Learn more about blocks in the Help Centre.

Can a delay be added to the code to slow the process?

**Comment by TheRealFlyingFrog** [comment]
I think the simplest way would be a „time.sleep(whatever)“ on line 504 
(Where whatever is number of seconds) 

That way it will iterate slower over the ids. 
I just found this project so I am still working on a few improvements

One could also replace the standard selenium with  https://github.com/SerpentAI/selenium-respectful

There are a few other techniques you can apply, one that I like to do is not acting like a robot 
So maybe throw in a few random clicks or scrolls on here or there. (Now this May be useless I am just guessing Facebook doesn’t just look at request count and headers to identify bots)

**Comment by InsaneJokerr** [comment]
Hi TheRealFlyingFrog, 

I've attempted the first solution but still got banned. Currently awaiting the ban to lift so I can make further tests. Have you found a solution yet? 

Also, I'm not 100% clued up with selenium, It's my first time using it. How would I go about switching out selenium to be used with selenium-respectful. Sorry if it's a stupid question.

**Comment by InsaneJokerr** [comment]
@TheRealFlyingFrog - Been playing with this further throughout the day. Looks like selenium-respectful won't be needed.

I've added a 20 seccond pause using "import time" "time.sleep(20)" where you mentioned in your  earlier post and I've continued to add 2/3 second pauses after each section (ie. photos, videos, about etc.)

I could usually only scrape around 7 profiles before being blocked. I'm currently on test number 7 of the day and i'm now on 40 profiles, so looks like I may have got it.

**Comment by anoduck** [comment]
Well,
@InsaneJokerr 42 profiles is more than I was able to accomplish. You must have a much faster network connection that I have, and were able to accomplish more before FB flagged you. As you brilliantly suggested, the `import time time.sleep(20)` on line 504 worked to help accomplish something other than being immediately blocked. I adjusted the time from 20 seconds to 31, hoping this would circumvent any adjusted flags by FB, but this did not work either, and only allowed me to get further along in the process but not complete it. I will make a vain attempt at adjusting the value again to 60 seconds, just to eliminate any inner nagging suspicions I have.   

The first suggestion I want to mention is using a random time amount to the variable between two variables, a min and a max. This way it would be difficult for FB to adjust their internal automated restrictions. Also it seemed that the wait time suggested only effected a few of the actions performed by the script, and should be performed by all actions performed by the script to prevent further adjustments by FB.   

Lastly, I noticed something interesting the other day, which I need to test again to confirm. But, I had opened up another browser window in chrome other than the one opened up with web driver. This performed to benefits, it prevented another error I had received when attempting to login, allowing the driver to use the cookie already required, and it appeared to resolve the issue of being blocked if an effort was made to browse the site actively and randomly while the script was running. I believe the two simultaneous instances with different interaction periods prevented the algorithm used by Facebook from being triggered. But, this might be a complete misunderstanding on my part.   

I am a complete novice programming python, but am tinkering with the script to see if I can provide any help toward solving this dilemma.

**Comment by InsaneJokerr** [comment]
@anoduck I haven't made much progress since my last comment, but I am currently working on some tests. I've already added a 60 sec delay between each scrape, and a 2/3 sec delay between each section (photos, posts, about etc.) - I was still banned. I think the random amount of time could be an option, and i'm looking at adding it to my next test, which I should be able to run this coming weekend. 

This week, I've cut the script down into separate .py processes, one just doing photos, one just doing posts etc. - I think the ban might be happening when it scrapes the about section of the profile, as it moves to quickly between Overview, Work and edu, places lived, contact info, family etc. 

I'm going to re-build the About section of the code so each tab has a pause in-between. I think if this does not work, I'll be stuck. 

At this point, adding any more than 62 seconds per profile seems like a pointless exercise if you are scraping a large amount of content. 5000 profiles could see the script running anywhere between 3-5 days, if it was running 24/7.

**Comment by anoduck** [comment]
I totally agree, >62 is too much, and makes the use of the script impractical. I must have really pushed it last night, because I am still blocked. I looked up the code needed to make the `time.sleep()` value randomized, and what I found was:
```
from random import randint
~~~
time.sleep(randint(5,29))
```
Brilliant work breaking everything down into individual scripts and with adding 2/3 sec delay!

Although, I did not find that the blocking occurred during the scraping of the "About" section. For me it occurred in the first process of scraping, during acquiring the profiles of friends. I am willing to bet that the differencing of our experiences in which the blocking occurred during the scraping of the "About" section for you, and the "Friends" section for me, reveals how the algorithm is working. That is, represented in crude symbolically logic format:
```
IFF user X queries Y times in Z minutes, THEN block.
WHERE Y and Z are proportionally related on a sliding scale.
So, IFF 200=Y in 5=Z, then block.
AND
IFF 500=Y in 7=Z, then block.
```
Which for FB would be a simple and effective means to counteract profile scraping. All this being said, the simply addition of a random value for `time.wait` is probably not going to resolve the issue. What will need to be done is adding the ability to count how many queries have been made in how many seconds, and then call a `time.wait(randinit(a, b))` as to force the script to pause for a random amount of time, throwing off this algorithm and not preceding past the point of being flagged. The point of all of this being, to emulate actual human interaction with the site as closely as possible while maintaining automation.

**Comment by anoduck** [comment]
Performing a little research I encountered that we are coming across a rate limit instituted by FB. I have encountered this before with facebook and do not know why it slipped my mind. One could use the ratelimit library available from pip to circumvent this restriction. Again, not a python programmer, just a unix junky, and these are just suggestions.

**Comment by anoduck** [comment]
@InsaneJokerr I believe I have found a work around, but currently am not able to test it, because of being temporarily blocked...again... Who knows how long the temporary block will last this time, last time it was a 36 hours, which is excessive.   
Anyways, I added the ratelimit library to the script which should assist in circumventing this restriction. Then worked with the code a little and figured how to use the library. Currently, at the top I imported the ratelimit library with:
```
from ratelimit import limits
from random import randint
```
Then around 51-ish:
```
# I added the call to the ratelimits library to apply to the function
@limits(calls=randint(13, 34), period=randint(600, 900))
def get_facebook_images_url(img_links):
    urls = []

    for link in img_links:
        if link != "None":
            valid_url_found = False
            driver.get(link)
``` 
Then around 81-ish:
```
@limits(calls=randint(13, 34), period=randint(600, 900))
def image_downloader(img_links, folder_name):
    img_names = []
```
Then around 294-ish:
```
# I added the call again to limit downloads for the function
@limits(calls=randint(13, 34), period=randint(600, 900))
def save_to_file(name, elements, status, current_section):
    """helper function used to save links to files"""
```
Then around 445-ish:
```
@limits(calls=randint(13, 34), period=randint(600, 900))
def scrape_data(user_id, scan_list, section, elements_path, save_status, file_names):
    """Given some parameters, this function can scrap friends/photos/videos/about/posts(statuses) of a profile"""
    page = []
```
Then, finally around 505-ish:
```
@limits(calls=randint(13, 34), period=randint(600, 900))
def scrap_profile(ids):
    folder = os.path.join(os.getcwd(), "Data")
    create_folder(folder)
    os.chdir(folder)
```

All of this should limit the amount of downloading and browsing actions are performed in the webdriver to a random integer between 13-24 calls for a random integer between ten and fifteen minutes. I have little faith that even if this works for now, that it will continue to work for a sustained amount of time. It is only a matter of time until Facebook changes its algorithm and this too will fail.   
There is probably a better and more programmatically way to do this, by defining a function to place a randomized ratelimit on all browsing/downloading actions. But for now, my patchwork job needs testing.  
More than likely, someone has found a means to work around this issue, but they are not sharing.

**Comment by anoduck** [comment]
@InsaneJokerr I have tried multiple strategies to circumvent this issue, and each time gotten absolutely nowhere.  

I have tried:  

1. adding more `time.sleep(whatever)` to the script
2. using `random` library to input a random integer into the time.sleep(whatever) call
3. facilitating the `ratelimits` library in multiple ways
4. combining the `ratelimits` library with the `random` library for variating limits on calls
5. swapping out the use of the standard `selenium` library with the `selenium-respectful` library as suggested by @TheRealFlyingFrog 

But no matter what I have done so far, the script flies right through the scraping process without any inhibitions, and eventually gets blocked. At this point, I am calling it quits for a while. I don't see how anyone can use it without resulting in the same problem of getting blocked before the script is able to complete. Maybe a full rewrite using selenium-requests with ratelimit might work, but I am doubtful and it is outside my pay grade. It appears to all be dead in the water regretfully.

**Comment by anoduck** [comment]
@InsaneJoker I got further than 42, in fact I was able to scrape through an estimated 252 profiles that were linked to a single input profile. But again I believe now that I was cutting too far of a margin attempting to reduce run times. It still appears that it will have to be slowed down to 30+ per profile to avoid the ban.

**Comment by anoduck** [comment]
**Correction** This method of scraping the book of face is sadly dead in the water. _In fact_, I wouldn't recommend anyone views the site in a browser on their desktop, and strictly limit their use to the app. Facebook's current rate limit strategy is so sensitive that practically any user attempting to "surf" profiles can and will trigger it. The end result being the ability to search and view other profiles besides one's own will be blocked for a 24 hour period. Once a user has been flagged for violation once, the rate limit monitor becomes even more sensitive specifically for that account. It appears the fun times are over, but what a rush it was.

@InsaneJokerr : You need to close out this issue brother. This issue has nothing to do with the developer of the script, and is the result of internal changes inside Facebook that are outside the control of the developer. Sad to say, it is over.

**Comment by InsaneJokerr** [comment]
@anoduck Sorry for late reply - have lost track of a few things. I think you stand correct. I've played with _selenium-respectful_ and whilst it did allow for further profiles to scrape, it was a very slow process, which would have been quicker to do without automation. 

A shame, would be keen to know if anyone finds any alternate ways to scrape this data.

Thanks to everyone for their input!

^IJ

**Comment by BabyRdx** [comment]
Been a while since I've used this but I ended up getting around this by having it sleep for a random amount of time between x and y.  Slows the process down a lot (obviously) but allowed me to fully automate the process.

**Comment by anoduck** [comment]
@BabyRdx I should probably fork the repo creating a new branch and post the full script with all the modifications that I made to it. I basically did the same thing, which allowed me to achieve 42 profiles before getting banned. Facebook has really toughened their algorithms for rate limiting, because once you get banned, it becomes even easier and faster to ban you again the next time. 

I believe that @InsaneJokerr had the right idea though, break the script down into portions, and only run the parts of the script that you need to.  But, I have some serious doubts as to the effectiveness of this strategy circumventing further blocking.

The only other solution I can see to this, is writing a script that performs a similar function inside an android emulated environment that uses the mobile app. Currently, the rate limit blocking is not employed or enforced in the mobile app. Which appears promising, but will require a full rewrite in a whole new framework. You might be able to simplify this entire proposed concept by simply incorporating tasker to do the same thing for you in a mobile phone. Anyways, that is my $0.35 worth.

**Comment by anoduck** [comment]
@BabyRdx I owe you an apology, your suggestion was very fruitful, and I was simply mistaken to dismiss it. I reviewed my modifications to the script, noticed where previously I had set some variables that would equate to running the script at a "snail's pace", tested it again with those "snail's pace" settings, and it appears to have successfully allowed me to complete a full scraping. Which is exciting! Slower than trying to pour frozen molasses, but exciting.

@InsaneJokerr, @BabyRdx was right! It works only if set to crawl at a "snail's pace".

**Comment by InsaneJokerr** [comment]
Glad we've got somewhere with this, nice job! I'll run a test tomorrow and report back with results. How many accounts did you scrape successfully out of interest? Did you calculate any average completion times? - Looking forward to testing tomorrow. :)

**Comment by BabyRdx** [comment]
@anoduck Thank you for the apology.  More than most people would ever do when realising an error.  

You idea of the Android app interests me.  Given I am not proficient in mobile app development I would have assumed it would still interacts with the Facebook server via http/https.  If this assumption holds true could you not test if the rate limiter is present in the webapp by spoofing the user agent to appear as it is the Facebook mobile app?  

@InsaneJokerr Impossible to calculate completion times as we can't clearly define what/how many content an average account is.  I have some friends with 3000+ pics and others with 20.

**Comment by anoduck** [comment]
@InsaneJokerr With the current set variables I traversed an average of 38 seconds per profile, which is faster than I anticipated. Regardless, the script ran all night and well into the afternoon of the following day. 
As for the total count of profiles traversed, that one is much more speculative, but somewhere between 243 and 323 profiles were traversed successfully, and appears too low to be correct.

@BabyRdx, Well, yes you could. The current useragent for the book of face mobile app is:
```
Mozilla/5.0 (Linux; Android 7.0; SM-G570M Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/192.0.0.34.85;]
```
via: https://developers.whatismybrowser.com/useragents/explore/software_name/facebook-app/

And one could use the extension Useragent switcher & manager to change the useragent for chromedriver for scraping. I have downloaded the extension, but too tired to work out how to add the facebook useragent string to the extension and set it to default. Once sucessfully accomplished, should be able to run some tests on that theory.

Another way, is to do so programitically within the script. Which is a better option. The tutorial on how to accomplish this is:
http://allselenium.info/how-to-setup-user-agent-in-python-selenium-webdriver/

**Comment by github-userx** [comment]
@BabyRdx

Your suggestion about the mobile app reminds me of this one: https://github.com/mgp25/Instagram-API

**Comment by anoduck** [comment]
Modified script to use fb's mobile app user-agent, done.
Modifications are posted to gist:

<script src="https://gist.github.com/anoduck/e9b0c0f04de58cb89aa3447e415bcb05.js"></script>

**Comment by anoduck** [comment]
## Report: After modifications to User Agent ##

Unfortunately, the modification to the user agent string had little to no effect on the scraping process from what was observed. Both the rate limit and time pause variables were modified to make a slightly faster scraping process, with an average time of 30 second per request. After scraping for hours the inevitable occurred, instead of informing the user (me) that he was blocked, a different message straight out of the pages of 1969 was displayed. Reading:

`--------------------------------------------------------------------------------`

#### You Can't Use This Feature Right Now ####

We limit how often you can post, comment or do other things in a given amount of time in order to help protect the community from spam. You can try again later. Learn More

P.S. Mark Zuckerburg is watching you.

`----------------------------------------------------------------------------------`

(I made that last bit up, just FYI)

All of which means, the rate limit still stands and was unaffected by the additional modification of the user string. 

But, the silver lining in all of this is you can still scrape as long as you are willing to traverse at a pace that is slower than watching paint dry in a rain storm. 

Well, there you have it, my $0.35 worth.

**Comment by github-userx** [comment]
@Anoduck for me using scripts and automation isn’t about speed but about the fact that I can just let it run in the background without having to do anything manually for hours. But yeah I remember the good old days when you could pretty much scrape everything without limits and especially how much access graphsearch gave us (most important for me was always facebook.com/search/userID/photos-tagged)

**Comment by anoduck** [comment]
Yeah, the ability to search those tagged photos was really something. I have actually been thinking about writing a script to perform a similar function to scrape those tagged images, add the ability to filter results based on a few parameters, and then provide the ability to analyze the data afterwards. It will be an uphill battle with a steep learning curve, as I am still very much a novice with writing python code. We will see what I can accomplish before my attention gets redirected elsewhere.

It doesn't make much of a difference for me, what pace the scraping occurs. A few seconds per scrape will add over an hour to several hours of scrape time, but when you have been scraping for over 8 hours straight, it makes little difference whether it takes 8 or 10 hours. 

I am just thankful that you still can use the script.

**Comment by milahu** [comment]
> Here is my copy of the script that includes the modifications made to slow down the script to a "snail's pace": https://gist.github.com/anoduck/e9b0c0f04de58cb89aa3447e415bcb05

```py
firefox_profile_path = "$HOME/.mozilla/firefox/0n8gmjoz.bot"
```
thats pseudo bash script syntax ....

in python you write
```py
import os
firefox_profile_path = os.getenv('HOME')+"/.mozilla/firefox/0n8gmjoz.bot"
```
the path suffix can be auto-detected with
```py
import os, glob
firefox_profiles = glob.glob(os.getenv('HOME')+"/.mozilla/firefox/*")
```
but then, why do we need firefox at all?
that `firefox_profile_path` variable looks like "ancient trash"

here is a `diff -u1` against the current `git head` version 68c1a20
to add
* random time delays
* rate limiting

```diff
--- scraper.py.orig	2019-12-21 16:26:27.962732532 +0100
+++ scraper.hackhack.2019-12-21.py	2019-12-21 16:31:30.811313832 +0100
@@ -1 +1,4 @@
+## You will need to install the ratelimit package from pip in the least to get this script to run successfully.
+## ALSO, you will need to ensure that chromedriver is in your current $PATH. For some reason this is now an issue.
+
 import calendar
@@ -7,2 +10,7 @@
 
+## Custom Imports for time banning.
+import time
+from random import randint
+from ratelimit import limits
+
 from selenium import webdriver
@@ -37,5 +45,17 @@
 old_height = 0
-firefox_profile_path = "/home/zeryx/.mozilla/firefox/0n8gmjoz.bot"
+
+#TODO remove
+#firefox_profile_path = "/home/zeryx/.mozilla/firefox/0n8gmjoz.bot"
+
 facebook_https_prefix = "https://"
 
+# Values for rate limiting | lower is slower!
+rtqlow = 9
+rtqhigh = 21
+rtime = 600
+
+# Traversal speed is solely controlled by this variable
+# Vales for time sleep in secs
+tsmin = 27
+tsmax = 42
 
@@ -48,2 +68,3 @@
 
+@limits(calls=randint(rtqlow, rtqhigh), period=rtime)
 def get_facebook_images_url(img_links):
@@ -54,2 +75,3 @@
             valid_url_found = False
+            time.sleep(randint(tsmin, tsmax))
             driver.get(link)
@@ -79,2 +101,3 @@
 # takes a url and downloads image from that url
+@limits(calls=randint(rtqlow, rtqhigh), period=rtime)
 def image_downloader(img_links, folder_name):
@@ -102,2 +125,5 @@
                     try:
+                        # Requesting images too fast will get you blocked too.
+                        time.sleep(randint(tsmin, tsmax))
+
                         urllib.request.urlretrieve(link, img_name)
@@ -233,2 +259,3 @@
 
+@limits(calls=randint(rtqlow, rtqhigh), period=rtime)
 def extract_and_write_posts(elements, filename):
@@ -342,2 +369,3 @@
 
+@limits(calls=randint(rtqlow, rtqhigh), period=rtime)
 def save_to_file(name, elements, status, current_section):
@@ -384,2 +412,3 @@
                             try:
+                                time.sleep(randint(tsmin, tsmax))
                                 driver.get(friend)
@@ -536,2 +565,3 @@
 
+@limits(calls=randint(rtqlow, rtqhigh), period=rtime)
 def scrape_data(user_id, scan_list, section, elements_path, save_status, file_names):
@@ -547,2 +577,3 @@
         try:
+            time.sleep(randint(tsmin, tsmax))
             driver.get(page[i])
@@ -614,2 +645,3 @@
 
+@limits(calls=randint(rtqlow, rtqhigh), period=rtime)
 def scrap_profile(ids):
@@ -622,2 +654,3 @@
 
+        time.sleep(randint(tsmin, tsmax))
         driver.get(user_id)
@@ -860,2 +893,3 @@
 
+@limits(calls=randint(rtqlow, rtqhigh), period=rtime)
 def scrapper(**kwargs):
```

**Comment by anoduck** [comment]
@milahu Many Thanks! I am completely inexperienced writing python, and was waiting and hoping for someone with more expertise to come along and review the work. 

I totally agree, that line referring to a firefox profile does not belong and appears to be archaic syntactical residue. I will make the revisions and upload it to gist later tonight.

I have also made modifications to the `tsmin` and `tsmax` variables increasing the difference between these two variables while maintaining a minimal pace of traversal around 30 seconds per profile. The greater span in the two variables provides more randomized variation in `time.sleep` thus providing better circumvention of rate limiting.

**Comment by anoduck** [comment]
Seeing that the overall structure of this repository has changed and several updates have been made to the script. I have gone ahead and forked the repository and made the modifications mentioned by @milahu above there. In the future I will be keeping modifications to the script on this repository and removing the previously linked gist.

https://github.com/anoduck/Ultimate-Facebook-Scraper

Enjoy.

**Comment by milahu** [comment]
> I have gone ahead and forked the repository

thanks! im too lazy as project maintainer

some random suggestions / todo items

* add `ratelimit` to dependencies in `setup.py`: `install_requires=["selenium==3.141.0", "pyyaml", "ratelimit"],`
* remove `requirements.txt`? seems useless, dependencies are defined in setup.py
* suggest shallow clone for download = `git clone --depth=1`
* replace `selenium` with `selenium-wire` to read/write http headers -- [project](https://github.com/wkeeling/selenium-wire) and [sample](https://stackoverflow.com/a/51919307/10440128). for example, with selenium, i cannot add `application/json` to the client's `accept` header, which would be useful in some exotic situations : P also better for testing and monitoring, e.g. monitor that chromium is not leaking private data
* only download platform-specific binaries. currently i get three versions for linux64, mac64 and win32
* keep track of state, use a sqlite database, flush often [commit database changes to disk often, so we dont lose data -- no problem for SSD drives]. tolerate unhandled exceptions [program crashes], allow to resume from last position, avoid re-downloading
* behave more "natural" and "human" while scraping .... this is probably the hardest part cos "what is human?" except solving captchas. facebook aint stupid, they will monitor this project, and train their defense systems to block our software. what i think of "as last resort" is a browser plugin, where you manually browse a profile, and the plugin saves all the data you visit, and also helps to "browse more" data, like "expand all comments". with that user behavior, the program can "learn" to act more human .... to apply a similar "browsing strategy" automatically to other profiles .... machine learning to the rescue

lots of room for improvement

**Comment by anoduck** [comment]
Thanks again,
Added suggestions to the project file todo.org, to plan for implementation at a later point in time.

**Comment by milahu** [comment]
> plan for implementation at a later point in time

rather not : P

just found this facebook scraper: https://github.com/rugantio/fbcrawl

pro:
* headless, no need for selenium or any GUI at all = low memory use, no need to download binary files [chromedriver], no need to mess with javascript / ajax requests
* no infinite scroll on https://mbasic.facebook.com/ = simple pagination = low memory use
* based on scrapy, the most popular python web scraping framework = "parallel approach" is already built in, using `yield` statements -- "pause and continue" should be easy to implement

con:
* project is currently unmaintained [ @anoduck ? ], there are [some active forks](https://techgaun.github.io/active-forks/index.html#https://github.com/rugantio/fbcrawl) with different improvements, that should be merged back to the original project
* the "mbasic" version of facebook has some minor limitations, that can be compensated by crawling the "m" [mobile] version at https://m.facebook.com/ -- this is on the project's todo list
* underrated, only 300 github stars, UFS has 1300 = overrated, but both projects started in year 2018

**Comment by anoduck** [comment]
@milahu Wow, that is a nice find. A lof of quality code there needing to be revived back to life. Without a doubt the facilitation of using mbasic.domain.com is a breakthrough, it provides many new opportunities. I have also heard good things about scrapy, and look forward to dabbling into it. This appears to be a better alternative to UFS, although this repository is more of a backend to build a more verbose framework off of.

Although, I am not quite sure if mbasic will provide any advantage to circumventing rate limiting? Will it?

I am also not sure what is the benefit to using `setup.py` over `requirements.txt`? It was my understanding that using `setup.py` installed the package to the system or virtual environment, and once this was done it could not be removed cleanly by executing `python3 setup.py uninstall`. I might be misunderstanding the point of the implementation. 

It was my thought to completely remove the chromedriver binaries from the repository because they are wasted space. Chromedriver has to matched with the chrome or chromium version that is installed on the system, and this varies from distro to distro. Just like you, I feel that firefox and the geckodriver is a better solution for this anyway. 

My main priority is writing a function that will stop the scraping process once the account has been notified it has been blocked. This will prevent the user from experiencing excessively lengthy bans. After completion, I would like to to return to building a means to filter targets by gender. For my convoluted purposes scraping a male profile is pointless.

Right now, previous made alterations to slow the script down in order to circumvent rate limiting are not working, and we may be back to being dead in the water again. 

Providing a side by side view of the scraping process and a web framework are a nicety that will provide aesthetic appeal to the project, but fall lower on the list of priorities than actually getting the process to be successful.

As for incorporating javascript for machine learning, I don't know javascript, so it will be difficult. 

Parrallel implementation and stateful tracking are a definite need for any scraping process. As of right now, if the scrape get's interrupted or blocked prematurely all of that information gets lost, and that totally sucks. 

@milahu, I had tried to invite you to be a contributor to the project so you can get credit for your ideas. Contribution does not necessarily require you to maintain the code base and respond to issues. 

I had written more, but my browser crashed and the message was unrecoverable. Thank your for the brilliant ideas.

**Comment by BabyRdx** [comment]
Just my 5c.  If I was writing this app I would make it threaded.  I would have a scheduler thread responsible for giving tasks to a working thread (only a single working thread is needed due to limiter) and a database handler thread.  The working thread would check a queue for a job and if not empty pick the first job from the queue.  A job for example could be scrape X photo etc.  The working thread would carry out the job and hand the data to the database handler thread to store/display/sort the data.

The database handler thread could write data directly to disk or store it in a simple database of sorts.  Storing it in a database would allow for a number of functions such as filtering users by gender.

I have to admit I am not the most knowledgeable in web scrapping but I feel staying with Selenium is your best bet as Facebook is known to dislike web scrapping.  As a result, other methods of web scraping would be easier to detect than Selenium which can easily mask as a human user.

**Comment by anoduck** [comment]
@BabyRdx You might find your $0.05 is actually worth $1.53. Those are great ideas. I am not sure exactly how to implement threads in python yet or go about modifying the current code base to where it would facilitate the use of threads. This is after all a "head first dive" into programming with python.   

As far as selenium vs. scrapy, I have knowledge not. It is sensical to assume that selenium would cloak the scraping process to allow the scraper to appear to be 'human'. By far I am not a scraping guru or even a scraping novice for that matter, rather just a mere trifle of a UNIX junkie. But, the case may be the primary identifier that denotes 'human' or not is the user agent string used.  From what little I know about rate limiting, the policy appears to depend on the simplified expression:  
```python

if:
  requests per timeperiod > x
    user = bot
  elif:
    requests per timeperiod < x
      user = human
```

Of coarse this is just a simplified example, and a thorough implementation can involve a much more complex algorithm defining both acceptable `requests` and acceptable `timeperiods`. But in summary to my over winded preponderance of the concept, I simply do not know. 

Regardless of the above, fbcrawl vanilla does not scrape and exists on 404 error. There might be a resolution to this somewhere in one of the forks. 

As usual, I am very thankful for the opportunity to discourse with other intelligent users of github, and am thankful for the thoughtful and courteous interaction you provide. Thank you for the dialogue and the contribution to intellectual creativity.

**Comment by InsaneJokerr** [comment]
Hey @anoduck, temporarily using a windows machine, I'm having an error on your quackified version that exits when it detects I'm using windows. How can I bypass this? I'm not familiar with this code.

**Comment by anoduck** [comment]
Yeah, you know what the problem is...your running Windows. I will uncomment the lines that provide the parameters to scrape with windows and will remove the prank "easter egg" error response I implanted. Just be aware, the scraping process is now slower than watching paint dry.

**Comment by anoduck** [comment]
@InsaneJokerr It is done. In order to scrape you must have `chromedriver.exe` in the same folder as scrape.py or the script will not be able to find it.

**Comment by InsaneJokerr** [comment]
@anoduck, jeez that is slow! might look at a rasperry pi to scrape on. Thinking this will use more in energy than it's worth!!

**Comment by anoduck** [comment]
@InsaneJokerr Don't blame me, I am just the messenger. The book of face has really clamped down hard on bots and scraping. You can always tweak the parameters to your own peril, they are just what I was able to discover to get the scraper rolling without getting banned, and it worked. I was able to successfully complete a scrape of several profiles in my input.txt. Each profile had over a thousand friends. Took me over 24 hours, but it worked.

**Comment by InsaneJokerr** [comment]
@anoduck, for sure, I'm not blaming you! Out of interest, how many profiles did you scrape in 24 hours?

**Comment by anoduck** [comment]
nine profiles were in input.txt and several of those profiles had over a thousand friends. So, the script traversed well over 2-3000 profiles in the course of it running.

**Comment by CharleoY** [comment]
@anoduck That's a good result since I didn't even finish with one profile and it showed that I can not use this feature.

**Comment by carlosalaniz** [comment]
>     * a

I tried the m.facebook website, it limits the amount of posts you can see ( in the case of groups and pages ), it's perfect to scrape user data and individual posts, I wrote my own nodeJS headless scrapper implementation and also got banned :( feel free to take a look at the code base. 
[](https://github.com/carlosalaniz/facebook-scrapper-nodejs)

This block appears to be web-only since I'm able to browser normally in my phone. I will be looking into emulating the calls made by the android app, MIM should tell me how the calls are different from the ones made by the browser.

**Comment by carlosalaniz** [comment]
> 
> 
> > plan for implementation at a later point in time
> 
> rather not : P
> 
> just found this facebook scraper: https://github.com/rugantio/fbcrawl
> 
> pro:
> 
>     * headless, no need for selenium or any GUI at all = low memory use, no need to download binary files [chromedriver], no need to mess with javascript / ajax requests
> 
>     * no infinite scroll on https://mbasic.facebook.com/ = simple pagination = low memory use
> 
>     * based on scrapy, the most popular python web scraping framework = "parallel approach" is already built in, using `yield` statements -- "pause and continue" should be easy to implement
> 
> 
> con:
> 
>     * project is currently unmaintained [ @anoduck ? ], there are [some active forks](https://techgaun.github.io/active-forks/index.html#https://github.com/rugantio/fbcrawl) with different improvements, that should be merged back to the original project
> 
>     * the "mbasic" version of facebook has some minor limitations, that can be compensated by crawling the "m" [mobile] version at https://m.facebook.com/ -- this is on the project's todo list
> 
>     * underrated, only 300 github stars, UFS has 1300 = overrated, but both projects started in year 2018

I tried the m.facebook website, it limits the amount of posts you can see ( in the case of groups and pages ), it's perfect to scrape user data and individual posts, I wrote my own nodeJS headless scrapper implementation and also got banned :( feel free to take a look at the code base.

This block appears to be web-only since I'm able to browser normally in my phone. I will be looking into emulating the calls made by the android app, MIM should tell me how the calls are different from the ones made by the browser.

**Comment by anoduck** [comment]
@carlosalaniz Greatly appreciate the information and the input. I look forward to hearing of your future developments. 

My modification of UFS 2.0 as of last week was still able to scrape without getting banned, it still is at an incredibly slow pace, but is faster than version 1.0. The UFS still is not able to scrape all publicly available images, which needs to be added later on.   
https://github.com/anoduck/Ultimate-Facebook-Scraper  

I did perform some work merging the progress made by several of the forks of fbcrawl, I still have one more to go which would facilitate the use of postgresql to store the data. It is currently untested.
